name: Deploy Medusa to-EC2-final-test

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Deploy Medusa on EC2 using Github actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Medusa to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.210.241.93 "
          # Navigate to the app directory
          cd /home/ubuntu/PearlThoughts-task/my-medusa-store &&
          
          # Pull the latest code
          git pull origin main &&

          # Step 3: Install PM2 globally if it's not already installed
          sudo npm install pm2@latest -g &&
          
          # Reinstall dependencies if needed
          npm install &&
          
          # Ensure PostgreSQL is running
          sudo systemctl start postgresql &&
          
          # Run migrations if required
          npx medusa migrations run &&
          
          # Build and restart the Medusa app
          npm run build &&
          pm2 restart medusa-app || pm2 start npm --name 'medusa-app' -- start
          "
